build_kernel: Check destination directory

diff --git a/build_kernel b/build_kernel
--- a/build_kernel
+++ b/build_kernel
@@ -106,6 +106,11 @@ function decode_cmdline_args {
       exit 1
     fi
   fi
+
+  if [[ ! -d $v_packages_destination ]]; then
+    >&2 echo "Invalid packages destination!"
+    exit 1
+  fi
 }
 
 function cache_sudo {
