build_kernel: Change messages for older configs search

diff --git a/build_kernel b/build_kernel
--- a/build_kernel
+++ b/build_kernel
@@ -304,6 +304,7 @@ function find_most_recent_config_version_available {
     source_config_file=$(find_local_config_file_for_version "$short_candidate_version")
 
     if [[ -n $source_config_file ]]; then
+      >&2 echo "Found local older config version $candidate_version."
       echo "$source_config_file"
       return
     fi
@@ -312,14 +313,15 @@ function find_most_recent_config_version_available {
     amd64_modules_package_link=$(find_amd64_modules_package_link "$candidate_version")
 
     if [[ -n $amd64_modules_package_link ]]; then
+      >&2 echo "Found packaged older config version ($candidate_version) in the PPA; downloading and extracting..."
       download_and_extract_config_file_from_modules_package "$amd64_modules_package_link"
       return
     else
-      >&2 echo "Module package not found for version v$candidate_version! Searching the previous version..."
+      >&2 echo "Module package not found for version $candidate_version!"
     fi
   done
 
-  >&2 echo "No config (module package) found for version $target_version"
+  >&2 echo "No config (module package) found for the required kernel!"
   exit 1
 }
 
