purge_trash: Notify and continue in case of error
Previously, if `trash-rm` failed, the procedure would stop.

diff --git a/purge_trash b/purge_trash
--- a/purge_trash
+++ b/purge_trash
@@ -38,6 +38,8 @@ while IFS= read -r line || [[ -n "$line" ]]; do
 
     file_basename=$(basename "$(echo "$line" | perl -lane 'print "@F[2..$#F]"')")
 
-    trash-rm "$file_basename"
+    if ! trash-rm "$file_basename"; then
+      echo "Could not remove \`$file_basename\` from the trash!"
+    fi
   fi
 done <<< "$(trash-list | sort)"
